### ISSUE TITLE
void-function nil

### ISSUE THREAD

**Issue by jabranham** [vermiculus/ghub-plus#3]
Having magithub enabled and calling magit-status results in an error `void-function nil`

I think this has something to do with `ghubp-get-repos-owner-repo` but haven't had time to look into it.

This only occured after updating ghub+ and apiwrap (from MELPA) just now.

**Comment by vermiculus** [comment]
Do you have a backtrace? I noticed some weirdness (this same error on Travis) with the apiwrap dependency since I pushed them at the same time – my *guess* is that MELPA pulled ghub-plus and not apiwrap (the former being sorted after the latter), but I don't really know.

Restarting the Travis build resolved the issue for me, but I don't know what your situation is.

**Comment by vermiculus** [comment]
Is this still happening for you after updating and everything?

**Comment by jabranham** [comment]
I just updated ghub+ this morning and it looks like this is fixed. Thanks!
